package assignment4.processors;

/**
 * Sensor Data is the data generated by the sensor
 * 
 * @author bonii
 *
 */
public class SensorReading {
	private float humidity;
	private float temperature;
	
	public float getHumidity() {
		return humidity;
	}
	public void setHumidity(float humidity) {
		this.humidity = humidity;
	}
	public float getTemperature() {
		return temperature;
	}
	public void setTemperature(float temperature) {
		this.temperature = temperature;
	}
}
